/**
 * 記事生成・デプロイモジュール (テンプレート方式)
 *
 * クォータ節約のため Gemini を使わずテンプレートにデータを流し込む。
 */

import { writeFile, readFile } from 'node:fs/promises';
import { exec } from 'node:child_process';
import { promisify } from 'node:util';
import { join } from 'node:path';

const execAsync = promisify(exec);
const HIPHOP_CWD = '/Users/ktamatzmoto/Desktop/hiphop';

/**
 * .astro ファイルの内容をテンプレートから生成する
 * @param {any} data
 * @returns {string}
 */
function buildAstroTemplate(data) {
  const { artist, title, year, lyrics } = data;
  let researchText = data.research;
  try {
    const parsed = JSON.parse(researchText);
    if (parsed && parsed.outputs && parsed.outputs[0] && parsed.outputs[0].text) {
      researchText = parsed.outputs[0].text;
    }
  } catch(e) {}
  // Escape for Astro JSX
  researchText = researchText.replace(/{/g, '&#123;').replace(/}/g, '&#125;');
  const research = researchText;
  const slug = title.toLowerCase().replace(/ /g, '-').replace(/[^a-z0-9-]/g, '');

  return `---
import LyricsBlock from '../../components/LyricsBlock.astro';
import SongLayout from '../../layouts/SongLayout.astro';
---

<SongLayout
  title="${title} 和訳・意味・スラング解説 | ${artist}"
  description="${artist}の「${title}」(${year})の歌詞和訳と解説。"
  slug="${slug}"
>
    <div id="lyrics"></div>

    <section class="mb-12">
      <h2 class="text-[var(--c-gold)] text-xs uppercase tracking-widest mb-5 border-b border-[var(--c-border)] pb-2">
        歌詞と解説
      </h2>
      <pre class="text-sm whitespace-pre-wrap text-[var(--c-muted)] leading-relaxed">
${lyrics || '歌詞データなし'}
      </pre>
    </section>

    <section class="mb-12">
      <h2 class="text-[var(--c-gold)] text-xs uppercase tracking-widest mb-5 border-b border-[var(--c-border)] pb-2">
        リサーチ結果
      </h2>
      <div class="prose prose-invert max-w-none text-sm leading-relaxed text-[var(--c-dim)]">
        ${research.replace(/\n/g, '<br />')}
      </div>
    </section>
</SongLayout>
`;
}

/**
 * 実際にファイルを生成し、Git Pushする
 * @param {string} jsonPath
 * @returns {Promise<{ success: boolean, error: string|null }>}
 */
export async function processAndDeploy(jsonPath) {
  try {
    const rawData = await readFile(jsonPath, 'utf-8');
    const data = JSON.parse(rawData);

    // 1. Astroコンテンツ生成 (テンプレート方式)
    console.log('  [Processor] Astroファイル生成中 (テンプレート方式)...');
    const astroContent = buildAstroTemplate(data);
    const slug = data.title.toLowerCase().replace(/ /g, '-').replace(/[^a-z0-9-]/g, '');
    const astroPath = join(HIPHOP_CWD, 'src/pages/songs', `${slug}.astro`);

    await writeFile(astroPath, astroContent, 'utf-8');
    
    // 2. songs.ts への自動追記 (簡易版)
    console.log('  [Processor] データの追記中...');
    const songsPath = join(HIPHOP_CWD, 'src/data/songs.ts');
    let songsTs = await readFile(songsPath, 'utf-8');
    
    const newEntry = `  { slug: '/songs/${slug}', title: '${data.title}', subtitle: '${data.artist} · ${data.year}', artists: '${data.artist}', tag: 'AutoGenerated', era: '00s以降', region: 'Unknown', producer: 'Unknown', bpm: 0, sample: null, album: '', mbid: null, artistSlug: '${data.artist.toLowerCase().replace(/ /g, '-')}', asin: null, pubDate: '${new Date().toISOString().split('T')[0]}' },\n] as const;`;
    
    if (!songsTs.includes(slug)) {
      songsTs = songsTs.replace('] as const;', newEntry);
      await writeFile(songsPath, songsTs, 'utf-8');
    }

    // 3. Git操作
    console.log('  [Processor] Git Push中...');
    const commands = [
      `git add .`,
      `git commit -m "Auto-add song: ${data.artist} - ${data.title}"`,
      `git push origin main`
    ];

    for (const cmd of commands) {
      await execAsync(cmd, { cwd: HIPHOP_CWD });
    }

    console.log('  [Processor] デプロイ完了');
    return { success: true, error: null };
  } catch (error) {
    console.error(`  [Processor] エラー: ${error.message}`);
    return { success: false, error: error.message };
  }
}
